name: Builds, tests & co

on:
  pull_request:

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        ocaml-compiler:
          - "4.14"

    runs-on: ${{ matrix.os }}

    env:
      PATHEXT: "env:LOCALAPPDATA/Microsoft/WinGet/Links/"

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Install winget
        uses: Cyberboss/install-winget@v1

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: kit-ty-kate/setup-ocaml@win52
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          allow-prerelease-opam: true
          opam-repositories: |
            default: https://github.com/dra27/opam-repository.git#windows-initial

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
